baseURL = 'http://jamesgotech.github.io'
languageCode = 'en-us'
title = 'DEV GOTECH PORTFOLIO'
theme = 'hugo-resume'

PygmentsCodeFences = true
PygmentsCodeFencesGuessSyntax = true
PygmentsStyle = "monokai"
enableGitInfo = false

[params]
address = "Anambra, Nigeria"
email = "jamesgotech@gmail.com"
favicon = "/favicon.ico"
firstName = "James"
lastName = "Anyalewechi"
phone = "(+234) 8103202050"
profileImage = "img/profile-photo.jpg"
showEducation = true
showExperience = true
showOpenSource = true
showProjects = true
showPublications = true
showQr = true
showSkills = true

[params.google]

[params.google.analytics]
trackerID = "XX-123446-01"

[[params.handles]]
link = "https://www.linkedin.com/in/james-anyalewechi/"
name = "LinkedIn"

[[params.handles]]
link = "https://github.com/jamesgotech/"
name = "GitHub"


#[[params.handles]]
#link = "https://bitbucket.org/eddiewebb/"
#name = "Bitbucket"

#[[params.handles]]
#link = "https://stackoverflow.com/users/story/82880"
#name = "Stack Overflow"

#[[params.handles]]
#link = "https://keybase.io/edwardawebb"
#name = "Keybase"

[outputs]
home = ["HTML", "JSON"]

[taxonomies]
tag = "tags"
